name: "Setup environment"
description: "Sets up environment for tardis and caches it"

inputs:
  os-label:
    description: "os label for lock file, default linux-64"
    required: true
    default: "linux-64"
  lock-file-url-prefix:
    description: "url for lock file, default tardis-base/master"
    required: false
    default: "https://raw.githubusercontent.com/tardis-sn/tardis-base/master/"

runs:
  using: "composite"
  steps:
      - name: Download Lock File
        run:  wget -q ${{ inputs.lock-file-url-prefix }}/conda-${{ inputs.os-label }}.lock
        shell: bash
      
      - name: Generate Cache Key
        run: | 
          file_hash=$(cat conda-${{ inputs.os-label }}.lock | shasum -a 256 | cut -d' ' -f1)
          echo "file_hash=tardis-conda-env-${{ inputs.os-label }}-${file_hash}-v1" >> "${GITHUB_OUTPUT}"
        id: cache-environment-key
        shell: bash
        
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-${{ inputs.os-label }}.lock
          cache-environment-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          cache-downloads-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          environment-name: tardis
          cache-environment: true
          cache-downloads: true
